---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:4.19.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: npm-install
  image: livingdocs/editor-base:18
  commands: ["npm install"]

- name: test
  image: livingdocs/editor-base:18
  commands: ["npm run test:ci -s"]

- name: build
  image: livingdocs/editor-base:18
  commands: ["npm run build -s"]

- name: release
  image: livingdocs/semantic-release:v1.2.2
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN

trigger:
  event: [push]
---
kind: signature
hmac: 84b017f54ccb2df1406b2bdecfed49a8105816784cc1e9157276baefd50e1382

...
