---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:4.19.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: npm-install
  image: livingdocs/editor-base:8.2
  commands: ["npm install"]

- name: test
  image: livingdocs/editor-base:8.2
  commands: ["npm run test:ci -s"]

- name: release
  image: livingdocs/semantic-release:v1.0.0
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN

trigger:
  event: [push]
---
kind: signature
hmac: f4880f26443a82eb8fb348304ec841357b27765613d36a20e1841a212c0a55aa

...
