---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:4.19.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: npm-install
  image: livingdocs/editor-base:8.2
  commands: ["npm install"]

- name: test
  image: livingdocs/editor-base:8.2
  commands: ["npm run test:ci -s"]

- name: set-build-info
  image: node:10
  commands: ["npx set-ci"]

- name: pre-release
  image: livingdocs/editor-base:8.2
  commands: ["git fetch --tags"]

- name: release
  image: marcbachmann/semantic-release:15.1.3
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN

trigger:
  event: [push]
---
kind: signature
hmac: 2c74a33a5080dae6dd718539c2a3dbf4662609791c5a8d6ba5c7001a9918226b

...
