---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:8.0.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: npm-install
  image: livingdocs/editor-base:22
  environment:
    PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
  commands: ["npm install"]

- name: test
  image: livingdocs/editor-base:22
  environment:
    CHROMIUM_PATH: /usr/bin/chromium-browser
  commands: ["npm run test:ci -s"]

- name: build
  image: livingdocs/editor-base:22
  commands: ["npm run build -s"]

- name: release
  image: livingdocs/semantic-release:v2.1.2
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN_PUBLISH

trigger:
  event: [push]
---
kind: signature
hmac: 93af62c974043ebe57c721e6fa1cc64b0fc513fa1a6ffd8c497b922fa5efe3c3

...
