---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:8.0.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: npm-install
  image: livingdocs/editor-base:18
  commands: ["npm install"]

- name: test
  image: livingdocs/editor-base:18
  commands: ["npm run test:ci -s"]

- name: build
  image: livingdocs/editor-base:18
  commands: ["npm run build -s"]

- name: release
  image: livingdocs/semantic-release:v2.1.2
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN_PUBLISH

trigger:
  event: [push]
---
kind: signature
hmac: 3358cb6e722460fcfa80f319c2fce6e0c842b00df676d88c0bb4d923af9b34c0

...
