---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:8.0.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: npm-install
  image: livingdocs/editor-base:18
  commands: ["npm install"]

- name: test
  image: livingdocs/editor-base:18
  commands: ["npm run test:ci -s"]

- name: build
  image: livingdocs/editor-base:18
  commands: ["npm run build -s"]

- name: release
  image: livingdocs/semantic-release:v2.1.2
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN

trigger:
  event: [push]
---
kind: signature
hmac: 6b7d5a5e13b2636eadd54b56b855fac94e68e7b3a44480a0bcc496b70857848e

...
