---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:9.35.0
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: npm-install
  image: livingdocs/editor-base:22
  environment:
    PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
  commands: ["npm install"]

- name: test
  image: livingdocs/editor-base:22
  environment:
    CHROMIUM_PATH: /usr/bin/chromium-browser
  commands: ["npm run test:ci -s"]

- name: build
  image: livingdocs/editor-base:22
  commands: ["npm run build -s"]

- name: release
  image: livingdocs/semantic-release:v2.1.2
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN_PUBLISH

trigger:
  event: [push]
---
kind: signature
hmac: 2a5c9554d7c26747178c3641d3237c83cb0e04e4bb424eab52c81e3bd54d35cb

...
